Repository Les-Cop1/my-setup, pull requests merged in 2022-12, with the labels that each got.

#79 :sparkles: Sort room list
  src/components/item/add-item.tsx
  src/components/item/edit-item.tsx
  src/components/layout/auth-layout.tsx
Labels: ✨ Feature

#80 :bug: Fix color of account edit
  src/pages/account/account.test.tsx.snap
  src/pages/account/account.tsx
Labels: 🐛 Bug

#81 :bug: Fix add image at item creation
  src/api/item.ts
  src/components/item/add-item.tsx
  src/components/item/edit-item.tsx
Labels: 🐛 Bug

#83 :bug: Fix button position in slideover
  src/components/item/add-item.tsx
  src/components/item/edit-item.tsx
Labels: 🐛 Bug

#85 :sparkles: Close menu on select - mobile
  src/components/common/navbar/components/navbar-item.tsx
  src/components/common/navbar/navbar.props.ts
  src/components/common/navbar/navbar.tsx
  src/components/layout/auth-layout.tsx
Labels: ✨ Feature

#82 :sparkles: Add useDocumentTitle Hooks
  public/index.html
  src/assets/locales/en.json
  src/assets/locales/fr.json
  src/components/layout/auth-layout.tsx
  src/pages/home/home.tsx
  src/pages/not-found/not-found.tsx
  src/pages/overview/overview.tsx
  src/pages/room/room.tsx
Labels: 👨‍💻 Tech, ✨ Feature

#87 :sparkles: items sort by name or price
  package.json
  src/assets/locales/en.json
  src/assets/locales/fr.json
  src/index.tsx
  src/pages/room/components/index.ts
  src/pages/room/components/item-card.tsx
  src/pages/room/room.tsx
  yarn.lock
Labels: ✨ Feature

#86 :bug: Fix date input in add item
  src/components/item/add-item.tsx
Labels: 🐛 Bug
